Medacademy/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medacademy.Models;
using Ma.ClassLibrary;
using Ma.EntityLibrary;
using System.IO;
using Newtonsoft.Json;
using Ma.ClassLibrary.Utility;

namespace Medacademy.Controllers
{
    public class QuestionController : Controller
    {
        public DateTime CurrentTime = TimeZoneInfo.ConvertTimeFromUtc(System.DateTime.Now.ToUniversalTime(), TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
        public MAEntities _Entities = new MAEntities();
        // GET: Question
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Question()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult GetQuestionView(long testId)
        {
            var model = new Medacademy.Models.QuestionAddModel();
            model.LevelID = testId;
            return PartialView("~/Views/Question/_pv_QuestionAdd.cshtml", model);
        }

        [HttpGet]
        public PartialViewResult GetAddQuestionView(long testId)
        {
            var model = new Models.QuestionAddModel();
            model.LevelID = testId;
            return PartialView("~/Views/Question/_pv_QuestionAdd_Level.cshtml", model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public object AddQuestion(QuestionAddModel model)
        {
            bool status = false;
            string msg = string.Empty;
            var level = _Entities.tb_Level.Where(z => z.LevelID == model.LevelID).FirstOrDefault();
            string dbQuestion = model.question.Replace("\n", "").Replace("\r", "");
            var question = _Entities.tb_Question.Create();
            var repQuestion = _Entities.tb_Question.Where(z => z.Question == dbQuestion).OrderByDescending(z => z.QuestionId).FirstOrDefault();
            if (repQuestion == null)

            {
                question.LevelID = level.LevelID;
                question.IsActive = true;
                question.Mark = 1;
                question.Question = model.question.Replace("\n", "").Replace("\r", "");
                question.QuestionTypeId = model.questionTypeId;
                question.TimeStamp = CurrentTime;
                question.Explanation = model.answerExplanation == null ? "" : model.answerExplanation.Replace("\n", "").Replace("\r", "");

                if (model.questionTypeId == 2 && model.questionImage != null && model.questionImage != string.Empty)
                {
                    string folderPath = Server.MapPath("~/Files/QuestionImage/");
                    if (!Directory.Exists(folderPath))
                        Directory.CreateDirectory(folderPath);
                    var imageString = model.questionImage.Substring(model.questionImage.IndexOf(',') + 1);
                    byte[] imageByte = Convert.FromBase64String(imageString);
                    string imageName = Guid.NewGuid().ToString() + ".jpeg";
                    var filePath = Server.MapPath("~/Files/QuestionImage/" + imageName);
                    var fileSave = "/Files/QuestionImage/" + imageName;

                    using (var imageFile = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.Write(imageByte, 0, imageByte.Length);
                        imageFile.Flush();
                        question.QuestionImage = fileSave;
                    }
                }
                if (model.ansExpImage != null && model.ansExpImage != string.Empty)
                {
                    string folderPath = Server.MapPath("~/Files/QuestionImage/");
                    if (!Directory.Exists(folderPath))
                        Directory.CreateDirectory(folderPath);
                    var imageString = model.ansExpImage.Substring(model.ansExpImage.IndexOf(',') + 1);
                    byte[] imageByte = Convert.FromBase64String(imageString);
                    string imageName = Guid.NewGuid().ToString() + ".jpeg";
                    var filePath = Server.MapPath("~/Files/QuestionImage/" + imageName);
                    var fileSave = "/Files/QuestionImage/" + imageName;

                    using (var imageFile = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.Write(imageByte, 0, imageByte.Length);
                        imageFile.Flush();
                        question.AnswerExpImage = fileSave;
                    }
                }
                _Entities.tb_Question.Add(question);
                status = _Entities.SaveChanges() > 0;
            }

            if (status && model.answerData != null && model.answerData != string.Empty)
            {
                var answerList = JsonConvert.DeserializeObject<List<ParseAnswer>>(model.answerData);
                if (model.answerTypeId == 1)
                {
                    foreach (var item in answerList)
                    {
                        var answer = _Entities.tb_Answer.Create();
                        answer.Answer = item.AnswerText;
                        answer.AnswerTypeId = model.answerTypeId;
                        answer.QuestionId = question.QuestionId;
                        answer.IsActive = true;
                        answer.TimeStamp = CurrentTime;
                        answer.RightStatus = item.AnswerStatus == true ? 1 : 0;
                        _Entities.tb_Answer.Add(answer);
                        _Entities.SaveChanges();
                    }
                }

                if (model.answerTypeId == 2)
                {
                    foreach (var item in answerList)
                    {
                        var answer = _Entities.tb_Answer.Create();
                        answer.Answer = string.Empty;
                        answer.AnswerTypeId = model.answerTypeId;
                        answer.QuestionId = question.QuestionId;
                        answer.RightStatus = item.AnswerStatus == true ? 1 : 0;
                        answer.IsActive = true;
                        answer.TimeStamp = CurrentTime;


                        string folderPath = Server.MapPath("~/Files/AnswerImage/");
                        if (!Directory.Exists(folderPath))
                            Directory.CreateDirectory(folderPath);
                        var imageString = item.AnswerText.Substring(item.AnswerText.IndexOf(',') + 1);
                        byte[] imageByte = Convert.FromBase64String(imageString);
                        string imageName = Guid.NewGuid().ToString() + ".jpeg";
                        var filePath = Server.MapPath("~/Files/AnswerImage/" + imageName);
                        var fileSave = "/Files/AnswerImage/" + imageName;

                        using (var imageFile = new FileStream(filePath, FileMode.Create))
                        {
                            imageFile.Write(imageByte, 0, imageByte.Length);
                            imageFile.Flush();

                            answer.AnswerImage = fileSave;


                        }
                        _Entities.tb_Answer.Add(answer);
                        status = _Entities.SaveChanges() > 0;

                    }
                }
                msg = status ? " Success!" : "Failed!";
            }



            return Json(new { status = status, msg = msg, id = model.LevelID }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public PartialViewResult RefreshAddQuestionView(long testId)
        {
            var model = new Models.QuestionAddModel();
            model.LevelID = testId;
            return PartialView("~/Views/Question/_pv_QuestionAdd_Level_Adding.cshtml", model);
        }

        [HttpGet]
        public PartialViewResult GetEditQuestionView(long questionId, long levelid)
        {
            var model = new Models.QuestionAddModel();
            var question = new Ma.EntityLibrary.Data.Question(questionId);
            var answer = question.GetAnswer().FirstOrDefault();
            model.LevelID = levelid;
            model.questionId = questionId;
            model.answerTypeId = answer.AnswerTypeId;
            model.questionTypeId = question.questionTypeId;
            return PartialView("~/Views/Question/_pv_Question_Edit.cshtml", model);
        }
        public object DeleteQuestion(long questionId)
        {
            bool status = false;
            string msg = string.Empty;
            var question = _Entities.tb_Question.Where(z => z.QuestionId == questionId && z.IsActive).FirstOrDefault();
            if (question != null)
            {
                question.IsActive = false;
                status = _Entities.SaveChanges() > 0;
                msg = status ? " Deleted!" : "Failed to delete!";

            }
            else
            {
                status = false;
                msg = "Failed to delete!";
            }
            return Json(new { status = status, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult RefreshQuestionsGrid(long testId)
        {
            var model = new Models.QuestionAddModel();
            model.LevelID = testId;
            return PartialView("~/Views/Question/_pv_QuestionAdd.cshtml", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public object EditQuestion(QuestionAddModel model)
        {
            bool status = false;
            string msg = string.Empty;

            //remove question
            var ansList = _Entities.tb_Answer.Where(z => z.QuestionId == model.questionId).ToList();
            foreach (var item in ansList)
            {
                item.IsActive = false;
               
            }
            _Entities.SaveChanges();

            var level = _Entities.tb_Level.Where(z => z.LevelID == model.LevelID).FirstOrDefault();

Medacademy/Views/Question/_pv_QuestionAdd.cshtml
@model Medacademy.Models.QuestionAddModel

@{
    var practiceTest = new Ma.EntityLibrary.Data.Level(Model.LevelID);
    var questions = practiceTest.GetQuestions();
}

<!-- Main content -->
<section class="content">
    <div class="box box-default">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list-alt"></i> Question List</h3>
            <button type="button" class="btn btn-success btn-xs pull-right" id="add-question-practice" data-practice-id="@Model.LevelID">Add Questions</button>
            <input type="hidden" id="hflevelid" value="@Model.LevelID" />
        </div>
        <div class="box-body">
            <table id="practQuestionTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Q No.</th>
                        <th>Question</th>
                        @*<th>Type</th>*@
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 1;
                    }
                    @foreach (var question in questions)
                    {
                        <tr>
                            <td>@index</td>
                            <td>@(new HtmlString(question.questionName))</td>
                            @*<td>
                                @if (question.GetAnswer().FirstOrDefault().AnswerTypeId == 2)
                            {
                                <p>Image</p>
                            }
                            else
                            {
                                <p>Text</p>
                            }
                        </td>*@
                        <td>
                            <button type="button" class="btn btn-success btn-xs edit-question" data-pract-id=@question.LevelID data-id="@question.questionId" data-practice-id="@Model.LevelID">Edit</button>
                            <button type="button" class="btn btn-danger btn-xs confirmDelete" data-id="@question.questionId">Delete</button>
                        </td>
                    </tr>
                        index++;
                    }
                </tbody>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->

<script>
    $(document).ready(function () {

        IntializeDataTable();

    });

    function IntializeDataTable() {
        $('#practQuestionTable').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true
            
        });
    }


</script>

Medacademy/Views/Question/_pv_QuestionAdd_Level_Adding.cshtml
@model Medacademy.Models.QuestionAddModel


<!-- Main content -->
<!-- COLOR PALETTE -->
<div class="box box-default color-palette-box">
    <div class="box-header with-border">
        <h3 class="box-title"><i class="fa fa-list-alt"></i> Add Question</h3>
        <button type="button" class="btn btn-success btn-xs pull-right" id="go-question-practice" data-practice-id="@Model.LevelID">Go Back</button>
    </div>
    <div class="box-body">
        @using (Ajax.BeginForm("AddQuestion", "Question", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "AddQuestionSuccess",
            OnFailure = "ajaxFailure",
        }, new { id = "form-login" }))
        {
            <div class="row" id="main-question-body">

                <div class="col-sm-12">
                    <!--- question type -->
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Question Type</label>
                            @Html.DropDownListFor(m => m.questionTypeId, Ma.EntityLibrary.Data.Dropdowndata.GetQuestionTypes(), "--Choose--", new { @class = "form-control select2" })
                        </div><!-- /.form-group -->
                    </div><!-- /.col -->
                    <!--- question type -->
                    <!--- answer type -->
                    <div class="col-md-4 isHidden" id="answer-type-id">
                        <div class="form-group">
                            <label>Answer Type</label>
                            @Html.DropDownListFor(m => m.answerTypeId, Ma.EntityLibrary.Data.Dropdowndata.GetAnswerTypes(), "--Choose--", new { @class = "form-control select2" })
                        </div><!-- /.form-group -->
                    </div><!-- /.col -->
                    <!--- answer type -->
                   </div>

                @Html.TextBoxFor(m => m.answerData, new { value = "", type = "hidden" })
                @Html.TextBoxFor(m => m.questionImage, new { value = "", type = "hidden" })
                @Html.HiddenFor(m => m.LevelID)

                @Html.TextBoxFor(m => m.answerExplanation, new { value = "", type = "hidden" })
                @Html.TextBoxFor(m => m.question, new { value = "", type = "hidden" })
                @Html.TextBoxFor(m => m.ansExpImage, new { value = "", type = "hidden" })




                <!--- html editor-->
                <div class="col-sm-12 isHidden" id="question-editor-area">
                    <div class="form-group">
                        <label>Question</label>
                        <textarea id="question-editor" name="question-editor" rows="10" cols="80"></textarea>
                    </div><!-- /.form-group -->
                </div>
                <!--- html editor-->
                <!--- image upload-->
                <div class="col-sm-12 isHidden" id="question-image-area">
                    <div class="form-group">
                        <label>Question Image</label>
                        <img style="height:100px;" id="question-image-preview" />
                        <input type="file" id="question-image-upload" />
                    </div><!-- /.form-group -->
                </div>
                <!--- image upload-->
                <!--- 2ndhtml editor-->
                <div class="col-sm-12 isHidden" id="question-editor-area2">
                    <div class="form-group">
                        <label>Question</label>
                        <textarea id="question-editor2" name="question-editor2" rows="10" cols="80"></textarea>
                    </div><!-- /.form-group -->
                </div>
                <!--- 2ndhtml editor-->


                <div class="col-sm-12 isHidden" id="answer-area">

                    <!--- answer clear template-->
                    <label>
                        Add Answers
                        <button type="button" class="btn btn-success btn-xs" onclick="AddQuestionOpt()"><i class="fa fa-plus"></i></button>
                    </label>
                    <div class="row" id="answer-editor-div">

                    </div>
                    <div class="row" id="answer-image-div">

                    </div>
                    <div class="form-group">
                        <label>Answer Explanation Image</label>
                        <img style="height:100px;" id="answer-exp-image-preview" />
                        <input type="file" id="answer-exp-image-upload" />
                        <label>Answer Explanation Text</label>
                        <textarea id="answer-explanation-editor" name="answer-explanation-editor" rows="10" cols="80"></textarea>
                    </div><!-- /.form-group -->

                </div>

                <button type="button" id="submit-btn-dummy" class="btn btn-info pull-right isHidden">Submit</button>
                <button type="submit" id="submit-btn" class="btn btn-info pull-right" style="display:none">Submit</button>
            </div><!-- /.row -->
        }

    </div><!-- /.box-body -->
    <div class="box-body">
    </div><!-- /.box-body -->
</div><!-- /.box -->
<!-- /.content -->


<script id="answer-clear-template" type="application/html-template">

</script>

Medacademy/Views/Question/_pv_Question_Edit.cshtml
@model Medacademy.Models.QuestionAddModel


@{
    var question = new Ma.EntityLibrary.Data.Question(Model.questionId);
    var answer = question.GetAnswer();

}

<input type="hidden" value="@answer.Count" id="hfAnswerCount" />

<!-- Main content -->
<section class="content">
    <!-- COLOR PALETTE -->
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list-alt"></i> Edit Question</h3>
            <button type="button" class="btn btn-success btn-xs pull-right" id="go-question-practice" data-practice-id="@Model.LevelID">Go Back</button>
        </div>
        <div class="box-body">
            <div class="row" id="main-question-body">
                @using (Ajax.BeginForm("EditQuestion", "Question", null, new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "EditQuestionSuccess",
                    OnFailure = "ajaxFailure",
                }, new { id = "form-login" }))
                {


                    <div class="col-sm-12">
                        <!--- question type -->
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Question Type</label>
                                @Html.DropDownListFor(m => m.questionTypeId, Ma.EntityLibrary.Data.Dropdowndata.GetQuestionTypes(), "--Choose--", new { @class = "form-control select2" })
                            </div><!-- /.form-group -->
                        </div><!-- /.col -->
                        <!--- question type -->
                        <!--- answer type -->
                        <div class="col-md-4" id="answer-type-id">
                            <div class="form-group">
                                <label>Answer Type</label>
                                @Html.DropDownListFor(m => m.answerTypeId, Ma.EntityLibrary.Data.Dropdowndata.GetAnswerTypes(), "--Choose--", new { @class = "form-control select2" })
                            </div><!-- /.form-group -->
                        </div><!-- /.col -->
                        <!--- answer type -->
                    </div>

                    @Html.TextBoxFor(m => m.answerData, new { value = "", type = "hidden" })
                    @Html.HiddenFor(m => m.LevelID)
                    @Html.HiddenFor(m => m.questionId)
                    @Html.TextBoxFor(m => m.questionImage, new { value = "", type = "hidden" })


                    @Html.TextBoxFor(m => m.answerExplanation, new { value = "", type = "hidden" })
                    @Html.TextBoxFor(m => m.question, new { value = "", type = "hidden" })
                    @Html.TextBoxFor(m => m.ansExpImage, new { value = "", type = "hidden" })

                    @*@Html.TextBoxFor(m => m.imageedit, new { value = "", type = "hidden" })*@


                    if (question.questionTypeId == 1)
                    {
                                    <!--- html editor-->
                        <div class="col-sm-12" id="question-editor-area">
                            <div class="form-group">
                                <label>Question</label>
                                <textarea id="question-editor" name="question-editor" rows="10" cols="80">@question.questionName</textarea>
                            </div><!-- /.form-group -->
                        </div>
                    <!--- html editor-->
                    }
                    else if (question.questionTypeId == 2)
                    {
                    <!--- image upload-->
                        {
                            var file = question.QuestionImage;
                            if (file != null)
                            {
                                <div class="col-sm-12" id="question-image-area">
                                    <div class="form-group">
                                        <label>Question Image</label>
                                        <img src="@file" style="height:100px" id="question-image-preview" />
                                        <input type="file" id="question-image-upload" />
                                        <input type="hidden" id="hfImageDatabase" value="1" />
                                    </div><!-- /.form-group -->
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12" id="question-image-area">
                                    <div class="form-group">
                                        <label>Question Image</label>
                                        <img style="height:100px;display:none;" id="question-image-preview" />
                                        <input type="file" id="question-image-upload" />
                                        <input type="hidden" id="hfImageDatabase" value="0" />
                                    </div><!-- /.form-group -->
                                </div>
                            }
                        }

                    <!--- image upload-->
                    <!--- 2ndhtml editor-->
                        <div class="col-sm-12" id="question-editor-area2">
                            <div class="form-group">
                                <label>Question</label>
                                <textarea id="question-editor" name="question-editor" rows="10" cols="80">@question.questionName</textarea>
                            </div><!-- /.form-group -->
                        </div>
                    <!--- 2ndhtml editor-->
                    }


                    <div class="col-sm-12" id="answer-area">
                        <label>
                            Add Answers
                            <button type="button" class="btn btn-success btn-xs" onclick="AddQuestionOpt()"><i class="fa fa-plus"></i></button>
                        </label>

                        @{
                            var index = 1;
                        }
                        @if (Model.answerTypeId == 1)
                        {
                            <div class="row" id="answer-editor-div">
                                @foreach (var ans in answer)
                                {
                                    <div class="form-group answer-editor-repeat" id="answer-editor-div-repeat-@index">
                                        <button class="btn btn-danger btn-xs remove-answer-option"><i class="fa fa-minus"></i></button>
                                        <label>Option</label>
                                        <textarea id="answer-editor-@index" name="answer-editor-@index">@ans.Answer</textarea>
                                        <input type="radio" name="correct-answer" id="correct-answer" @(ans.Status == 1 ? "checked" : "") />
                                    </div><!-- /.form-group -->
                                    index++;
                                }
                            </div>
                          
                        }
                        else if (Model.answerTypeId == 2)
                        {
                            <div class="row" id="answer-image-div">
                                @foreach (var ans in answer)
                                {
                                    var file = ans.AnswerImage;
                                    <div class="form-group answer-image-repeat" id="answer-editor-div-repeat-@index">
                                        <button class="btn btn-danger btn-xs remove-answer-option"><i class="fa fa-minus"></i></button>
                                        <label>Option</label>
                                        <input id="answer-image-@index" name="answer-image-@index" class="answer-image-upload" type="file" />
                                        <img style="height:100px;" src="@file" id="image-browse" />
                                        <input type="hidden" id="hfBase64Image" />
                                        <input type="hidden" id="hfIsDatabase" value="1" />
                                        <label>Correct Answer <input type="radio" name="correct-answer" id="correct-answer" class="radio radio-primary" @(ans.Status == 1 ? "checked" : "") /></label>
                                    </div><!-- /.form-group -->
                                    index++;
                                }
                            </div>
                        }

                        <div class="form-group">

                            <label>Answer Explanation Image</label>
                            @{
                                var answerExpImage = question.AnswerExpImage;
                                if (answerExpImage != null)
                                {
                                    <img style="height:100px;" id="answer-exp-image-preview" src="@answerExpImage" />
                                    <input type="hidden" id="hfExpImageDatabase" value="1" />
                                }
                                else
                                {
                                    <img style="height:100px;" id="answer-exp-image-preview" />
                                    <input type="hidden" id="hfExpImageDatabase" value="0" />
                                }
                                <input type="file" id="answer-exp-image-upload" />
                            }
                            <label>Answer Explanation</label>
                            <textarea id="answer-explanation-editor" name="answer-explanation-editor" rows="10" cols="80">@question.explanation</textarea>
                        </div><!-- /.form-group -->
                    </div>
                    <button type="button" id="submit-btn-dummy" class="btn btn-info pull-right ">Submit</button>
                    <button type="submit" id="submit-btn" class="btn btn-info pull-right" style="display:none">Submit</button>
                                }
            </div><!-- /.row -->
                               

        </div><!-- /.box-body -->
        <div class="box-body">
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section><!-- /.content -->


<script id="answer-editor-template" type="application/html-template">
    <div class="form-group answer-editor-repeat" id="answer-editor-div-repeat-{{item}}">
        <button class="btn btn-danger btn-xs remove-answer-option"><i class="fa fa-minus"></i></button>
        <label>Option</label>
        <textarea id="answer-editor-{{editorId}}" name="answer-editor-{{editorName}}" />
        <input type="radio" name="correct-answer" id="correct-answer" />
    </div><!-- /.form-group -->
</script>

<script id="answer-image-template" type="application/html-template">
    <div class="form-group answer-image-repeat" id="answer-editor-div-repeat-{{item}}">
        <button class="btn btn-danger btn-xs remove-answer-option"><i class="fa fa-minus"></i></button>
        <label>Option</label>
        <input id="answer-image-{{editorId}}" name="answer-image-{{editorName}}" class="answer-image-upload" type="file" />
        <img style="height:100px;" id="image-browse" />
        <input type="hidden" id="hfBase64Image" />
        <input type="hidden" id="hfIsDatabase" value="0" />
        <label>Correct Answer <input type="radio" name="correct-answer" id="correct-answer" class="radio radio-primary" /></label>
    </div><!-- /.form-group -->
</script>

<script>



</script>