Medacademy/Models/AddQuestoExam.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medacademy.Models
{
    public class AddQuestoExam
    { 

        public long ID { get; set; }
        public long LevelID { get; set; }
        public long QuestionId { get; set; }
        public long ExamId { get; set; }
        public string ExamName { get; set; }
        public bool IsActive { get; set; }
        public long QuestionCount { get; set; }
        public long CourseId { get; set; }
        public string CourseName { get; set; }

        public string Question { get; set; }

        public string SelectedData { get; set; }

    }
}

Medacademy/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medacademy.Models;
using Ma.ClassLibrary;
using Ma.EntityLibrary;
using System.IO;
using Ma.EntityLibrary.Data;
using System.Globalization;

namespace Medacademy.Controllers
{
    public class ExamController : Controller
    {
        public DateTime CurrentTime = TimeZoneInfo.ConvertTimeFromUtc(System.DateTime.Now.ToUniversalTime(), TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
        public MAEntities _Entities = new MAEntities();

        // GET: Exam
        public ActionResult Exam()
        {
            return View();
        }

        [HttpPost]
        public object AddExam(ExamModel model)
        {


            bool status = false;
            string msg = string.Empty;
            try
            {
                var exam = new tb_Exam();
                exam.ExamName = model.ExamName;
                exam.Duration = model.Duration;
                exam.TimeStamp = CurrentTime;
                exam.IsActive = true;
                exam.ActiveStatus = true;


                /* Converting Date time to Utc Time to avoid server timechange in future*/

                //DateTime stdate = Convert.ToDateTime(model.StartDate);
                //DateTime endate = Convert.ToDateTime(model.EndDate);





                //DateTime utcstartDateTime = TimeZoneInfo.ConvertTimeToUtc(stdate, TimeZoneInfo.Local);
                //DateTime utcendDateTime = TimeZoneInfo.ConvertTimeToUtc(endate, TimeZoneInfo.Local);

                /* Converting Date time to Utc Time to avoid server timechange in future*/

                exam.ExamStartDate = model.StartDate;// Convert.ToDateTime(model.StartDate).ToString("dd-MM-yyyy HH:mm"); //utcstartDateTime.ToString(); 
                exam.ExamEndDate = model.EndDate; //Convert.ToDateTime(model.EndDate).ToString("dd-MM-yyyy HH:mm"); //utcendDateTime.ToString();
                exam.UpcomingStatus = true;
                exam.PublishStatus = false;
                exam.PublishResult = false;


                _Entities.tb_Exam.Add(exam);
                status = _Entities.SaveChanges() > 0;
                {
                    if (model.GroupData != "" && model.GroupData != string.Empty && model.GroupData != null)
                    {
                        string[] splitData = model.GroupData.Split('~');
                        foreach (var item in splitData)
                        {
                            var group = _Entities.tb_ExamGroup.Create();
                            group.ExamId = exam.ExamId;
                            group.GroupId = Convert.ToInt64(item);
                            group.IsActive = true;

                            _Entities.tb_ExamGroup.Add(group);
                            _Entities.SaveChanges();
                            msg = "Success";
                            status = true;
                        }

                    }
                }
            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
            return Json(new { status = status, msg = msg }, JsonRequestBehavior.AllowGet);
        }


        public object ExamCancel(long examid)
        {
            bool status = false;
            string msg = string.Empty;
            var topics = _Entities.tb_Exam.Where(z => z.ExamId == examid && z.IsActive).FirstOrDefault();
            if (topics != null)
            {
                topics.ActiveStatus = false;
                status = _Entities.SaveChanges() > 0;
                msg = status ? " Exam Canceled!" : "Failed to Cancel!";
            }
            else
            {
                status = false;
                msg = "Failed to Cancel!";
            }
            return Json(new { status = status, msg = msg }, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult RefreshExam()
        {
            return PartialView("~/Views/Exam/_pv_Exam_Grid.cshtml", new Medacademy.Models.LevelsModel());
        }

        public ActionResult AddQuestoExam(string examid)
        {
            string[] splitData = examid.Split('~');
            var model = new Medacademy.Models.AddQuestoExam();
            model.ExamId = Convert.ToInt32(splitData[0]);
            model.ExamName = splitData[1].ToString();
            return View(model);
        }

        [HttpGet]
        public PartialViewResult GetQuestionView(long testId)
        {
            var model = new Medacademy.Models.AddQuestoExam();
            model.LevelID = testId;
            return PartialView("~/Views/Exam/_pv_ExamQuestionView.cshtml", model);
        }
        [HttpPost]
        public object AddQuesttoExam(AddQuestoExam model)
        {
            bool status = false;
            string msg = string.Empty;
            try
            {
                if (model.SelectedData != "" && model.SelectedData != string.Empty && model.SelectedData != null)
                {
                    string[] splitData = model.SelectedData.Split('~');
                    foreach (var item in splitData)
                    {
                        //var ExamQuestion = _Entities.tb_ExamQuestion.Create();
                        int questionid = Convert.ToInt32(item);
                        int examid = Convert.ToInt32(model.ExamId);
                        string exname = model.ExamName;
                        var ExamQuestion = _Entities.tb_ExamQuestion.Where(z => z.ExamId == model.ExamId && z.QuestionId == questionid).FirstOrDefault();
                        if (ExamQuestion == null)
                        {
                            var ExamQuestion1 = new tb_ExamQuestion();
                            ExamQuestion1.ExamId = examid;
                            ExamQuestion1.ExamName = exname;
                            ExamQuestion1.QuestionId = Convert.ToInt64(item);

                            _Entities.tb_ExamQuestion.Add(ExamQuestion1);
                            _Entities.SaveChanges();
                            msg = "Success";
                            status = true;
                        }
                        else
                        {
                            msg = "Question already Exists";
                            status = false;
                            break;
                        }
                    }

                }

            }
            catch (Exception ex)
            {
                msg = ex.Message;
            }
            return Json(new { status = status, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult RefreshExamQuestionGrid(long testId)
        {
            var model = new Models.AddQuestoExam();
            model.LevelID = testId;
            return PartialView("~/Views/Exam/_pv_ExamQuestionView.cshtml", model);
        }

        public PartialViewResult PreparationView(string examid)
        {
            string[] splitData = examid.Split('~');
            var model = new Medacademy.Models.Preparation();
            model.examid = Convert.ToInt32(splitData[0]);
            model.examname = splitData[1].ToString();
            var preparation = _Entities.tb_Preparation.Where(z => z.ExamId == model.examid && z.IsActive).FirstOrDefault();
            if (preparation != null)
            {
                model.stdate = preparation.StartDate;
                model.eddate = preparation.EndDate;
            }
            return PartialView("~/Views/Exam/_pv_Add_Preparation.cshtml", model);
        }

        [HttpPost]
        public object AddPreparation(Preparation model)
        {
            bool status = false;
            string msg = string.Empty;

            var Preparation = _Entities.tb_Preparation.Where(z => z.ExamId == model.examid && z.IsActive).FirstOrDefault();
            if (Preparation == null)
            {

                var prep = new tb_Preparation();
                prep.ExamId = Convert.ToInt32(model.examid);
                prep.StartDate = model.stdate;
                prep.EndDate = model.eddate;
                prep.IsActive = true;
                prep.Timestamp = CurrentTime;
                prep.Duration = model.timer;
                prep.PreparationName = model.Name;

                _Entities.tb_Preparation.Add(prep);
                status = _Entities.SaveChanges() > 0;



                msg = status ? "Preparation added successfully!" : "Failed to add Preparation!";

            }
            else
            {
                msg = "Preparation already Exists";
                status = false;

            }
            return Json(new { status = status, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult ViewQuestion(string examid)
        {
            string[] splitData = examid.Split('~');
            var model = new Medacademy.Models.AddQuestoExam();
            model.ExamId = Convert.ToInt32(splitData[0]);
            model.ExamName = splitData[1].ToString();

            return PartialView("~/Views/Exam/_pv_ExamAllQuestionView.cshtml", model);
        }


        [HttpGet]
        public PartialViewResult RefreshExamQuestionCount(string examid)
        {
            string[] splitData = examid.Split('~');
            var model = new Models.AddQuestoExam();
            model.ExamId = Convert.ToInt32(splitData[0]);
            model.LevelID = Convert.ToInt32(splitData[1]);
            return PartialView("~/Views/Exam/_pv_Exam_QuestionCount.cshtml", model);
        }

        public PartialViewResult EditExamView(long examid)
        {
            var exam = _Entities.tb_Exam.Where(z => z.ExamId == examid && z.IsActive).FirstOrDefault();
            var model = new Medacademy.Models.ExamModel();
            model.ExamID = exam.ExamId;
            model.ExamName = exam.ExamName;
            model.StrtDate = exam.ExamStartDate;

Medacademy/Views/Exam/ExamResult.cshtml
@model Medacademy.Models.ExamModel
@{
    ViewBag.Title = "ExamResult";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var exam = new Ma.EntityLibrary.Data.Exam(Model.ExamID);
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <ol class="breadcrumb">                      
                        <li class="active"><h3 class="box-title">Result</h3></li>
                    </ol>
                    @{
                        <a class="btn btn-success btn-xs btn-publish-result" style="margin-left:5px" data-id="@Model.ExamID">Publish Result</a>
                    }
                </div><!-- /.box-header -->
                <div class="box-body" id="exam-result-list-view">
                    @Html.Partial("~/Views/Exam/_pv_ExamResult_Grid.cshtml", Model)
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->


<script>
    $(document).on('click', '.btn-publish-result', function () {
        var examId = $(this).attr("data-id");
        var url = '/Exam/PublishResult?examId=' + examId;
        $.confirm({
            text: "Are you sure?",
            confirm: function (button) {
                $.get(url, function (result) {
                    if (result.status) {
                        toastrSuccess(result.msg);
                       // refreshExamResultGrid();
                        //$('.btn-publish-result').addClass('isHidden');
                        //$('.btn-result-conceal').removeClass('isHidden');
                    }
                    else {
                        toastrError(result.msg);
                    }
                });
            },
            confirmButton: "Yes",
            cancelButton: "Cancel",
            confirmButtonClass: "btn-danger",
            cancelButtonClass: "btn-success",
        });
    });
</script>

Medacademy/Views/Exam/_pv_Add_Preparation.cshtml
@model Medacademy.Models.Preparation

<div class="modal-dialog modal-md">
    <div class="modal-content" style="border-radius: 3px;">
        @using (Ajax.BeginForm("AddPreparation", "Exam", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "AddPreparationSuccess",
                OnFailure = "AddPreparationFailed",
            }, new { id = "form-login" }))
            {
            <div class="modal-body">
                <form>
                    @*@Html.TextBoxFor(m => m.examid, new { type = "hidden",value=@Model.examid })*@
                    @Html.HiddenFor(z => z.examid, new { Value = @Model.examid })
                    <div class="modal-header view-header text-center">
                        Exam Name<span aria-hidden="true" style="margin-left:5px; font-weight:600;">@Model.examname</span>
                    </div>
                    <div style="margin:10px 5px;">
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Preparation</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", Placeholder = "Preparation" })
                                @Html.ValidationMessageFor(m => m.timer)
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Duration</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(m => m.timer, new { @class = "form-control", Placeholder = "Duration", Value = "00:00:00" })
                                @Html.ValidationMessageFor(m => m.timer)
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Start Date</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(m => m.stdate, new { @class = "form-control", id = "stdate", placeholder = "MM/DD/YYYY" })
                                @Html.ValidationMessageFor(m => m.stdate)
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">End Date</label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(m => m.eddate, new { @class = "form-control", id = "eddate", placeholder = "MM/DD/YYYY" })
                                @Html.ValidationMessageFor(m => m.eddate)
                            </div>
                        </div>
                        
                    </div>
               

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger " data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </form>

            </div>
        }
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->




<script>

    $('#addPreparation').on('shown.bs.modal', function () {

        $('#stdate').datetimepicker({
            format: 'DD-MM-YYYY HH:mm',
            minDate: new Date()
        });
        $('#eddate').datetimepicker({
            format: 'DD-MM-YYYY HH:mm',
            minDate: new Date()
        });

       
        $('#eddate').datetimepicker({ format: 'DD/MM/YYYY' }).on('dp.change', function (e) {

          
            var startdate = $('#stdate').val();
                var enddate = $('#eddate').val();
                if(startdate>enddate)
                {
                    toastrError("End date lessthan start date!");
                }
        });

        $('#stdate').datetimepicker({ format: 'DD/MM/YYYY' }).on('dp.change', function (e) {

            
            var startdate = $('#stdate').val();
            var enddate = $('#eddate').val();
            if (enddate != "") {
                
                if (startdate > enddate) {
                    toastrError("End date lessthan start date!");
                }
            }
        });
    });




</script>

Medacademy/Views/Exam/_pv_ExamAllQuestionView.cshtml
@model Medacademy.Models.AddQuestoExam

@{
    var questions = new Ma.EntityLibrary.Data.ExamQuestion().GetQuestions(@Model.ExamId);

}

<section class="content">
    <div class="box box-default">
        <div class="box-body">
            <input type="hidden" id="hflevelid" value="@Model.LevelID" />
            <div class="modal-header view-header">
                Questions <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <table id="QuestionTableNew" class="table table-bordered table-striped">

                <thead>
                    <tr>
                        @*<th><input class="selectall" type="checkbox"></th>*@
                        <th>Q No.</th>
                        <th>Question</th>
                      
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 1;
                    }
                    @foreach (var question in questions)
                    {
                        <tr>
                            @*<td><input class="ckb-question-item" value="@question.QuestionId" type="checkbox"></td>*@
                            <td>@index</td>
                            <td>@(new HtmlString(question.Question))</td>
                           
                        </tr>
                        index++;
                    }
                </tbody>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
    @*<div class="btns-qstexam">


        <button type="button" class="btn btn-success" id="btn-dummy-addexam">Add to Exam</button>
        <button type="submit" style="display:none;" id="btn-addexam" class="btn btn-success">Save</button>
        <button type="button" class="btn btn-danger">Publish</button>

    </div>*@
</section>


<script>
    $(document).ready(function () {


        IntializeDataTable();


    });






    function IntializeDataTable() {
        $('#QuestionTableNew').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "lengthMenu": [5, 10, 50, 100, 200, "Max"],
            "pageLength": 5,
            "aoColumnDefs": [{ "bSortable": false, "aTargets": [0] }]

        });

    }


</script>

Medacademy/Views/Exam/_pv_ExamEdit.cshtml
@model Medacademy.Models.ExamModel
@{
    var grpdata = Model.GroupData;
}
<div class="modal-dialog modal-md">
    <div class="modal-content" style="border-radius: 3px;">
        <div class="modal-header">
            Edit Topic<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>

        @using (Ajax.BeginForm("EditExam", "Exam", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "EditExamSuccess",
            OnFailure = "EditExamFailed",
        }, new { id = "form-login" }))
        {
            @Html.HiddenFor(z => z.GroupData, new { Value = grpdata, id ="grdata" })
            @Html.TextBoxFor(m => m.ExamID, new { type = "hidden" })
            @Html.TextBoxFor(m => m.GroupDataEdit, new { type = "hidden" })

            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Exam Name</label>
                        <div class="col-sm-8">
                            @*<input type="text" class="form-control" placeholder="Test">*@
                            @Html.TextBoxFor(m => m.ExamName, new { @class = "form-control", placeholder = "Exam Name" })
                            @Html.ValidationMessageFor(m => m.ExamName)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Duration</label>
                        <div class="col-sm-8">
                            @*<input type="text" class="form-control" placeholder="Test">*@
                            @Html.TextBoxFor(m => m.Duration, new { @class = "form-control", placeholder = "In minutes", Value = "00:00:00" })
                            @Html.ValidationMessageFor(m => m.Duration)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Start Date</label>
                        <div class="col-sm-3">

                            @Html.TextBoxFor(m => m.StrtDate, new { @class = "form-control", id = "StrtDate" })
                            @Html.ValidationMessageFor(m => m.StrtDate)

                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">End Date</label>
                        <div class="col-sm-3">

                            @Html.TextBoxFor(m => m.EnDate, new { @class = "form-control", id = "EnDate" })
                            @Html.ValidationMessageFor(m => m.EnDate)

                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Groups</label>
                            <div class="dropdown_main">
                                <span class="dropdown_btn">Groups <i class="fa fa-caret-down"></i></span>
                                <ul class="dropdown_lists">
                                    @foreach (var groups in new Ma.EntityLibrary.Data.Group().GetGroups())
                                    {
                                        <li>
                                            <label class="label_container">
                                                @groups.GroupName
                                                <input type="checkbox" value="@groups.GroupID" class="chk-roles-cls-edit">
                                                <span class="checkmark"></span>
                                            </label>
                                        </li>
                                    }
                                </ul>

                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">&nbsp;</label>
                        <div class="col-sm-8">


                            <button type="button" id="btn-dummy-addexam1" class="btn pay-now-btn">Update</button>
                            <button type="submit" style="display:none;" id="btn-addexam1" class="btn btn-success">Save</button>
                            <button type="button" class="btn btn-danger" onclick="CloseLevel()">Close</button>
                        </div>
                    </div>

                </form>

            </div>


        }
    </div>
</div>

<script type="text/javascript">

    $('#editExam').on('shown.bs.modal', function () {

        $('#StrtDate').datetimepicker({
            format: 'DD-MM-YYYY HH:mm'

        });
        $('#EnDate').datetimepicker({
            format: 'DD-MM-YYYY HH:mm'

        });
    });

</script>





<script>
   

    $('.dropdown_btn').click(function () {
        $(this).siblings().toggle();
    });





</script>

Medacademy/Views/Exam/_pv_ExamQuestionView.cshtml
@model Medacademy.Models.AddQuestoExam

@{
    var practiceTest = new Ma.EntityLibrary.Data.Level(Model.LevelID);
    var questions = practiceTest.GetQuestions();
}

<section class="content">
    <div class="box box-default">
        <div class="box-body">
            <input type="hidden" id="hflevelid" value="@Model.LevelID" />
           
            <table id="QuestionTableNew" class="table table-bordered table-striped">
               
                <thead>
                    <tr>
                        <th><input class="selectall" type="checkbox"></th>
                        <th>Q No.</th>
                        <th>Question</th>
                        @*<th>Type</th>*@
                        @*<th>Action</th>*@
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 1;
                    }
                    @foreach (var question in questions)
                    {
                        <tr>
                            <td><input class="ckb-question-item" value="@question.questionId" type="checkbox"></td>
                            <td>@index</td>
                            <td>@(new HtmlString(question.questionName))</td>
                            @*<td>
                                    <button type="button" class="btn btn-success btn-xs edit-question" data-pract-id=@question.LevelID data-id="@question.questionId" data-practice-id="@Model.LevelID">Edit</button>
                                    <button type="button" class="btn btn-danger btn-xs confirmDelete" data-id="@question.questionId">Delete</button>
                                </td>*@
                        </tr>
                        index++;
                    }
                </tbody>
            </table>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
    <div class="btns-qstexam">
        @*<button type="submit" class="btn btn-success">Add to Exam</button>
        <button type="button" class="btn btn-danger " data-dismiss="modal" style="margin-right:10px">Publish</button>*@

        <button type="button" class="btn btn-success" id="btn-dummy-addexam" >Add to Exam</button>


        <button type="submit" style="display:none;" id="btn-addexam" class="btn btn-success">Save</button>
        <button type="button" class="btn btn-danger"  onclick="PublishExam()">Publish</button>

    </div>
</section>


<script>
    $(document).ready(function () {


        IntializeDataTable();


    });
  
  
       



    function IntializeDataTable() {
        $('#QuestionTableNew').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "lengthMenu": [5, 10, 50, 100, 200, "Max"],
            "pageLength": 5,
            "aoColumnDefs": [{"bSortable": false,"aTargets": [0]}]

        });

    }


</script>

Medacademy/Views/Exam/_pv_ExamResult_Grid.cshtml
@model Medacademy.Models.ExamModel
@{
    var examResult = new Ma.EntityLibrary.Data.Exam().GetUserResult(Model.ExamID);
    var exam = new Ma.EntityLibrary.Data.Exam(Model.ExamID);
}

<table id="examResultTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Mark</th>
            <th>Time(Seconds)</th>
            <th>Rank</th>
        </tr>
    </thead>
    <tbody>
        @{var index = 1;}
        @foreach (var user in examResult)
        {
            <tr>
                <td>@user.Name</td>
                <td>@user.Total</td>
                <td>@user.Examtime</td>
                <td>@index</td>
            </tr>
            index++;
        }
    </tbody>
</table>

Medacademy/Views/Exam/_pv_Exam_QuestionCount.cshtml
@model Medacademy.Models.AddQuestoExam
@{
    int count = new Ma.EntityLibrary.Data.ExamQuestion().GetCount(Model.ExamId);
    string exam = @Model.ExamName;
    var examid = new Ma.EntityLibrary.Data.Exam().GetExamsById(Model.ExamId);
    
}
<div class="row">
    <div class="col-sm-6">
        <div class="exam_name">
            <label class="col-form-label">Exam Name</label>
            <label class="col-form-label">@examid.FirstOrDefault().ExamName</label>
        </div>

    </div>
    <div class="col-sm-6">
        <div class="exam_name">
            <label class="col-form-label">Question Count</label>
            <label class="col-form-label">@count</label>
        </div>
    </div>
</div>