Medacademy/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Medacademy.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Medacademy/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medacademy.Models
{

    public class Login
    {
        [Required(ErrorMessage = "Required")]
        [EmailAddress(ErrorMessage = "Entered e-mail is not a valid mail")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Password { get; set; }

    }
}

Medacademy/Models/Preparation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medacademy.Models
{
    public class Preparation
    {
        [Required(ErrorMessage = "Start Date Required")]
        public string stdate { get; set; }

        [Required(ErrorMessage = "End Date Required")]
        public string eddate { get; set; }

        public DateTime timestamp { get; set; }

        public long preparationid { get; set; }

        public long examid { get; set; }

        public string examname { get; set; }
        public bool Isactive { get; set; }

        public TimeSpan timer { get; set; }

        [Required(ErrorMessage = "Name Required")]
        public string Name { get; set; }
    }
}

Medacademy/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medacademy.Models;
using Ma.ClassLibrary;
using Ma.EntityLibrary;
using Medacademy.Repository;
using Medacademy.Repository.Paytm;
using System.Web.Security;

namespace Medacademy.Controllers
{
    public class AccountsController : Controller
    {
        public DateTime CurrentTime = TimeZoneInfo.ConvertTimeFromUtc(System.DateTime.Now.ToUniversalTime(), TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
        public MAEntities _Entities = new MAEntities();
        UserRepository UserRepository = new UserRepository();
        // GET: Accounts
        public ActionResult Index()
        {
            PaginationRepository PaginationRepository = new PaginationRepository();
            PaginationModel PaginationModel = new PaginationModel();
            var datas1 = (UserModel)Session["UserLoginFirstTime"];
            var datas = datas1;
            try
            {
                if (datas != null)
                {
                    PaginationModel.CourseID = (long)datas.CourseId;
                    datas.PaginationModel = PaginationModel;
                    datas.Home_Pacages_List = PaginationRepository.Home_PakagesLists(PaginationModel);
                    //Session["UserLoginFirstTime"] = datas;
                    return View(datas);
                }

                List<PackageModel> LI_Pacages = new List<PackageModel>();
                UserModel models = new UserModel();

                LI_Pacages = PaginationRepository.Home_PakagesLists(PaginationModel);
                models.Home_Pacages_List = LI_Pacages;
                Session["Localsession"] = models;

                return View(models);

            }
            catch (Exception ex)
            {
                return RedirectToAction("SessionExpired", "User");
            }


        }
        public ActionResult Courses()
        {
            var datas = (UserModel)Session["UserLoginFirstTime"];
            try
            {
                if (datas != null)
                {
                    PaginationRepository PaginationRepository = new PaginationRepository();
                    var var_CourseModel = _Entities.tb_Course.Where(x => x.CourseId == datas.CourseId && x.IsActive == true).ToList();

                    PaginationModel PaginationModel = new PaginationModel();
                    var datas3 = _Entities.tb_Course.Where(x => x.CourseId == datas.CourseId && x.IsActive == true).Count();
                    PaginationModel.TotalItems = datas3;
                    CourseModel Co = new CourseModel();
                    Co.PaginationModel = PaginationModel;
                    PaginationModel.CourseID = datas.CourseId;
                    datas.CourseModel = Co;
                    datas.CourseModel_Lists = PaginationRepository.CoursesLists(PaginationModel);
                    Session["UserLoginFirstTime"] = datas;

                    return View(datas);
                }

                var models = (UserModel)Session["Localsession"];
                if (models == null || models.LocalModel.PaginationModel == null)
                {//Login
                    return RedirectToAction("SessionExpired", "User");
                }
                return View(models);

            }
            catch (Exception ex)
            {
                return RedirectToAction("SessionExpired", "User");
            }


        }
        public ActionResult Packages()
        {
            var datas = (UserModel)Session["UserLoginFirstTime"];
            try
            {
                if (datas != null)
                {
                    return View(datas);
                }

                var models = (UserModel)Session["Localsession"];
                if (models == null || models.LocalModel.PaginationModel == null)
                {//Login
                    return RedirectToAction("SessionExpired", "User");
                }
                if (models.LocalModel.LI_Pacages == null)
                {
                    return RedirectToAction("Local_Courses");
                }
                return View(models);

            }
            catch (Exception ex)
            {
                return RedirectToAction("SessionExpired", "User");
            }


        }
        public ActionResult Local_Courses(long? CourseId)
        {
            PaginationRepository PaginationRepository = new PaginationRepository();
            UserModel model = new UserModel();
            if (CourseId == null)
            {
                PaginationModel PaginationModel = new PaginationModel();
                LocalModel LocalModel = new LocalModel();
                var datas3 = _Entities.tb_Course.Where(x => x.IsActive == true).Count();

                PaginationModel.TotalItems = datas3;


                LocalModel.PaginationModel = PaginationModel;
                LocalModel.CourseModel_Lists = PaginationRepository.CoursesLists(PaginationModel);
                model.LocalModel = LocalModel;
            }
            else
            {
                PaginationModel PaginationModel = new PaginationModel();
                LocalModel LocalModel = new LocalModel();
                var datas3 = _Entities.tb_Course.Where(x => x.CourseId == CourseId && x.IsActive == true).Count();

                PaginationModel.TotalItems = datas3;
                PaginationModel.CourseID = (long)CourseId;

                LocalModel.PaginationModel = PaginationModel;

                LocalModel.CourseModel_Lists = PaginationRepository.CoursesLists(PaginationModel);
                model.LocalModel = LocalModel;

            }
            Session["Localsession"] = model;
            return RedirectToAction("Courses");
        }

        public ActionResult Local_Packages(long? CourseId)
        {
            PaginationRepository PaginationRepository = new PaginationRepository();
            UserModel model = new UserModel();
            if (CourseId == null)
            {
                PaginationModel PaginationModel = new PaginationModel();
                LocalModel LocalModel = new LocalModel();
                var datas3 = _Entities.tb_Package.Where(x => x.Isactive == true).Count();

                PaginationModel.TotalItems = datas3;


                LocalModel.PaginationModel = PaginationModel;
                LocalModel.LI_Pacages = PaginationRepository.PakagesLists(PaginationModel);
                model.LocalModel = LocalModel;
            }
            else
            {
                PaginationModel PaginationModel = new PaginationModel();
                LocalModel LocalModel = new LocalModel();
                var datas3 = _Entities.tb_Package.Where(x => x.CourseID == CourseId && x.Isactive == true).Count();

                PaginationModel.TotalItems = datas3;
                PaginationModel.CourseID = (long)CourseId;

                LocalModel.PaginationModel = PaginationModel;

                LocalModel.LI_Pacages = PaginationRepository.PakagesLists(PaginationModel);
                model.LocalModel = LocalModel;

            }
            Session["Localsession"] = model;
            return RedirectToAction("Packages");
        }

        public ActionResult Preparation()
        {
            return View();
        }
        public ActionResult Reports()
        {
            return View();
        }
        public ActionResult Groups()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            return View();
        }
        public ActionResult CreateAccount_User(UserModel model)
        {
            PaginationRepository PaginationRepository = new PaginationRepository();
            bool status = false;
            string msg = string.Empty;

            List<PackageModel> LI_PackageModel = new List<PackageModel>();

            string dirFullPath = HttpContext.Server.MapPath("~/Files/UserImg");
            var FilesName = UserRepository.UploadFiles(model.file, dirFullPath);
            string sessionID = SessionClass.SessionId();
            try
            {
                var create = _Entities.tb_Login.Create();
                if (FilesName != null)
                {
                    create.FilesName = "/Files/UserImg/" + FilesName.ToString();                    
                    model.FilesName = FilesName.ToString();
                }

                create.FirstName = model.FirstName;
                create.Email = model.Email;
                create.Password = model.Password;
                create.CourseId = model.CourseId;
                create.Districts = model.Districts;
                create.Pin = model.Pin;
                create.State = model.State;
                create.Address = model.Address;
                create.ContactNo = model.ContactNo;
                create.SessionId = sessionID;
                create.Gender = model.Gender;

                create.IsActive = true;
                create.TimeStamp = DateTime.Now;

                create.RoleId = (int?)SessionClass.Users.User;

                _Entities.tb_Login.Add(create);
                _Entities.SaveChanges();

                status = true;
                msg = "Success";

                model.SessionId = sessionID;
                model.IsActive = true;
                model.RoleId = (int)SessionClass.Users.User;

                PaginationModel PaginationModel = new PaginationModel();
                var datas3 = _Entities.tb_Package.Where(x => x.CourseID == model.CourseId && x.Isactive == true).Count();

                PaginationModel.TotalItems = datas3;

Medacademy/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medacademy.Models;
using Ma.ClassLibrary;
using Ma.EntityLibrary;
using System.IO;
using Ma.EntityLibrary.Data;
using System.Globalization;

namespace Medacademy.Controllers
{
    public class ReportController : Controller
    {
        public DateTime CurrentTime = TimeZoneInfo.ConvertTimeFromUtc(System.DateTime.Now.ToUniversalTime(), TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
        public MAEntities _Entities = new MAEntities();
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserExamReult()
        {         
            return View();
        }

        public ActionResult ExamWiseReport(string id)
        {           
            ExamModel model = new ExamModel();
            model.ExamID = Convert.ToInt64(id);
            return View(model);
        }
        public ActionResult ExamReview(string id)
        {
            var userData = (Medacademy.Models.UserModel)Session["UserLoginFirstTime"];
            string[] splitData = id.Split('~');
            SubmitExamModel model = new SubmitExamModel();
            model.userId = userData.UserId;          
            model.ExamId = Convert.ToInt64(splitData[0]);
            model.QuestionId = Convert.ToInt64(splitData[1]);
            ViewBag.Navigate = 1.ToString();
            //return View("StartPractice", model);
            return View(model);
        }
    }
}

Medacademy/Views/Accounts/Login.cshtml
@model Medacademy.Models.Login
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<section class="lgn_sec">

    @*@using (Ajax.BeginForm("LoginCheck", "Accounts", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "LoginCheckSuccess",
            OnFailure = "LoginCheckFailed"
        }, new { id = "form-login" }))
        {*@
    @using (Html.BeginForm("LoginCheck", "Accounts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="container">
            <div class="row">
                <div class="col-12 full_wid">
                    <div class="cust_lg_form">
                        <div class="details">

                            <h4>Login!</h4>
                            <div class="form-group">
                                @*<input type="text" class="form-control" placeholder="Email">*@
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                                @Html.ValidationMessageFor(m => m.Email)
                            </div>
                            <div class="form-group">
                                @*<input type="text" class="form-control" placeholder="Password">*@
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                                @Html.ValidationMessageFor(m => m.Password)
                            </div>
                            <p>Don’t  have an account ?  <span><a href="/Accounts/SignUp" class="btn-class">Sign up</a> </span></p>
                            <div class="sb_btn form-group">
                                @*<a href="#">login</a>*@
                                <button type="submit" class="btn-class">Login</button>
                            </div>

                        </div>


                        <div class="blue_right_sec">
                            <div class="img_cont">
                                <img src="~/Content/images/login/lgo.png">
                            </div>
                            <h4>
                                WELCOME TO
                                MEDACADEMY
                            </h4>
                            <p class="hid">To keep connected with us please signup with peronal info</p>
                            <div class="sb_btn form-group ">
                                <a href="/Accounts/SignUp" class="btn-class">Sign up</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</section>



<script>
            function LoginCheckSuccess(result) {
               // alert("test");
                //debugger;
                if (result.status) {
                    if (result.userType == 1) {
                        //toastr.info(result.msg);
                         window.location.href = '/Admin/Dashboard';
                    }
                    else if (result.userType == 2) {

                        // window.location.href = '/Parent/Home';
                    }
                }
                else {
                    //$('#errorMsg').removeClass("isHidden");
                    toastrError(result.msg);
                }
            }
            function LoginCheckFailed(result) {
                toastrError(result.msg);
            }


            //$(document).ready(function () {

            //    alert("test");

            //});


</script>

Medacademy/Views/Accounts/Preparation.cshtml
@{
    ViewBag.Title = "Preparation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Preparation</h2>

Medacademy/Views/Accounts/Reports.cshtml
@{
    ViewBag.Title = "Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="breadcrumbsSection report_section">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="breadcrumbs">
                    <h1>reports</h1>
                    <ul>
                        <li><a href="/Accounts/Index">Home</a></li>
                        <li>reports</li>
                    </ul>
                </div><!-- ./breadcrumbs -->

            </div>
        </div>
    </div>
</section>
<!-- ./breadcrumbsSection -->
<section class="report_sec">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="report_cust">
                    <h5>
                        Instant Review Reports help gauge
                        your overall performance!
                    </h5>
                    <p>Medacademy’s detailed reports give an insight into your progress when you take practice tests in a chosen subject. They provide reliable data and information on the knowledge and skills that you have acquired through your practice sessions on Medacademy. They also offer a better perspective on individual needs and achievements.</p>
                    <div class="lst_cust">
                        <ul>
                            <li><i class="fas fa-circle"></i>You can view the detailed report after every practice session.</li>
                            <li>
                                <i class="fas fa-circle"></i>The report helps find strengths as well as areas requiring
                                more practice.
                            </li>
                            <li>
                                <i class="fas fa-circle"></i>Report provides information on attended questions as well
                                the right and wrong responses.
                            </li>
                            <li>
                                <i class="fas fa-circle"></i>The report’s review option helps view the response and the
                                correct answer as well.
                            </li>
                            <li><i class="fas fa-circle"></i>The review also provides an explanation for the wrong responses.</li>
                            <li>
                                <i class="fas fa-circle"></i>The review option helps to correct one’s approach and do
                                better next time.
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="cmptr_img">
                    <img src="~/Content/images/reports/Untitled-4.png">
                </div>
            </div>
        </div>
    </div>
</section>

Medacademy/Views/Accounts/SignUp.cshtml
@model Medacademy.Models.UserModel

@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

@*testsibi1111111111111111111111111111111*@
<section class="lgn_sec">
    <div class="container">
        <div class="row">
            <div class="col-12 full_wid">
                <div class="cust_lg_form">
                    <div class="blue_right_sec blx_cust">
                        <div class="img_cont">
                            <img src="~/Content/images/login/lgo.png">
                        </div>
                        <h4>
                            WELCOME TO
                            MEDACADEMY
                        </h4>
                        <p class="hid">To keep connected with us please Login with peronal info</p>
                        <div class="sb_btn form-group">
                            <a href="/Accounts/Login" class="btn-class">Login</a>

                        </div>
                    </div>

                    @*@using (Ajax.BeginForm("CreateAccount_User", "Accounts", null, new AjaxOptions
                        {
                            HttpMethod = "POST",
                            OnSuccess = "LoginSuccess",
                            OnFailure = "LoginFailed",
                        }, new { id = "form-login" }))
                        {*@
                    @using (Html.BeginForm("CreateAccount_User", "Accounts", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="details dtlz_czt">
                            <form>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <h4>Create Account</h4>
                                    </div>
                                    <div class="col-lg-6 mar_rgt">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", placeholder = "Name" })
                                            @Html.ValidationMessageFor(m => m.FirstName)
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                                            @Html.ValidationMessageFor(m => m.Email)
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mar_rgt">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                                            @Html.ValidationMessageFor(m => m.Password)
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @Html.DropDownListFor(m => m.CourseId, Ma.EntityLibrary.Data.Dropdowndata.GetCourseDrop(), "--Choose--", new { @class = "form-control pv_class-drop-down", @data_live_search = "true", name = "topicDropdown", id = "topicDataDropdown" })
                                            @Html.ValidationMessageFor(m => m.CourseId)
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mar_rgt">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Districts, new { @class = "form-control", placeholder = "Districts" })
                                            @Html.ValidationMessageFor(m => m.Districts)
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Pin, new { @class = "form-control", placeholder = "Pin" })
                                            @Html.ValidationMessageFor(m => m.Pin)
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mar_rgt">
                                        <div class="form-group">

                                            @Html.TextBoxFor(m => m.State, new { @class = "form-control", placeholder = "State" })
                                            @Html.ValidationMessageFor(m => m.State)
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control", placeholder = "Address" })
                                            @Html.ValidationMessageFor(m => m.Address)
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mar_rgt">
                                        <div class="form-group">
                                            @Html.TextBoxFor(m => m.ContactNo, new { @class = "form-control", placeholder = "Contact No" })
                                            @Html.ValidationMessageFor(m => m.ContactNo)
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            @Html.DropDownListFor(m => m.Gender, Ma.EntityLibrary.Data.Dropdowndata.GetGender(), "--Choose--", new { @class = "form-control pv_class-drop-down", @data_live_search = "true", name = "topicDropdown", id = "topicDataDropdown" })
                                            @Html.ValidationMessageFor(m => m.Gender)
                                        </div>
                                    </div>
                                    <div class="col-lg-12 filz">
                                        <div class="form-group">
                                            @* <input type="file" class="custom-file-input">*@
                                            @*@Html.TextBox("file", "", new { type = "file", @class = "custom-file-input" }) <br />*@
                                            @Html.TextBoxFor(m => m.file, new { @class = "form-control custom-file-input", type = "file", placeholder = "File", id = "subtopic-pdf-upload" })
                                            @*<input id="subtopic-pdf-upload" type="file" class="uploder-controler" />*@

                                        </div>
                                    </div>

                                </div>
                                <div class="sb_btn sb_btnzz form-group" style="align-items:center;">
                                    <button type="submit" class="btn btn-success">Sign Up</button>
                                </div>
                            </form>
                        </div>
                    }


                </div>
            </div>
        </div>
    </div>
</section>

<script>
    function LoginSuccess(result) {
        if (result.status) {
            //$('#editLevel').modal('hide');
            toastrSuccess(result.msg);

        }
        else {
            toastrError(result.msg);
        }
    }
    function LoginFailed() {
        toastrError('Login Failed');
    }

    //$(document).on('change', '#subtopic-pdf-upload', function () {
    //    debugger;
    //    var source = $(this);
    //    var selectedFile = this.files[0];
    //    var input = this;
    //    if (input.files && input.files[0]) {
    //        var url = input.value;
    //        var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
    //        if (ext == "pdf") {
    //            selectedFile.convertToBase64(function (base64) {
    //                // $('#package-img-preview').attr({ "src": base64, "class": "useruploder" });
    //                $('#Pdfpath').val(base64);
    //            });
    //            var reader = new FileReader();
    //        }
    //        else {
    //            $(source).val('');
    //            toastrWarning('Invalid Filetype');
    //        }
    //    }
    //});

</script>